---
- name: All roles
  hosts: localhost
  gather_facts: yes
  roles:
    - repos
    - atom
    - bluejeans
    - chrome
    - firefox
    - spotify
    - multimedia
    - packages
#    - misc
#    - gsettings
#    - dotfiles
#    - scripts
